//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace scaffolder.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("scaffolder.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {
        ///	&quot;Logging&quot;: {
        ///		&quot;IncludeScopes&quot;: false,
        ///		&quot;Debug&quot;: {
        ///			&quot;LogLevel&quot;: {
        ///				&quot;Default&quot;: &quot;Warning&quot;
        ///			}
        ///		},
        ///		&quot;Console&quot;: {
        ///			&quot;LogLevel&quot;: {
        ///				&quot;Default&quot;: &quot;Warning&quot;
        ///			}
        ///		}
        ///	},
        ///	&quot;ConnectionStrings&quot;: {
        ///		&quot;[DbName]DB&quot;: &quot;[ConnectionString]&quot;
        ///	}
        ///}.
        /// </summary>
        internal static string appSettings {
            get {
                return ResourceManager.GetString("appSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;Project Sdk=&quot;Microsoft.NET.Sdk.Web&quot;&gt;
        ///	&lt;PropertyGroup&gt;
        ///		&lt;TargetFramework&gt;netcoreapp2.0&lt;/TargetFramework&gt;
        ///	&lt;/PropertyGroup&gt;
        ///
        ///	&lt;ItemGroup&gt;
        ///		&lt;Folder Include=&quot;wwwroot\&quot; /&gt;
        ///	&lt;/ItemGroup&gt;
        ///
        ///	&lt;ItemGroup&gt;
        ///		&lt;PackageReference Include=&quot;EntitySearch&quot; Version=&quot;1.0.0&quot; /&gt;
        ///		&lt;PackageReference Include=&quot;Microsoft.AspNetCore.All&quot; Version=&quot;2.0.3&quot; /&gt;
        ///	&lt;/ItemGroup&gt;
        ///
        ///	&lt;ItemGroup&gt;
        ///		&lt;DotNetCliToolReference Include=&quot;Microsoft.VisualStudio.Web.CodeGeneration.Tools&quot; Version=&quot;2.0.1&quot; /&gt;
        ///	&lt;/ItemGroup&gt;
        ///
        ///&lt;/Project&gt;.
        /// </summary>
        internal static string csProject {
            get {
                return ResourceManager.GetString("csProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {
        ///	&quot;iisSettings&quot;: {
        ///		&quot;windowsAuthentication&quot;: false,
        ///		&quot;anonymousAuthentication&quot;: true,
        ///		&quot;iisExpress&quot;: {
        ///			&quot;applicationUrl&quot;: &quot;http://localhost:[Port]/&quot;,
        ///			&quot;sslPort&quot;: 0
        ///		}
        ///	},
        ///	&quot;profiles&quot;: {
        ///		&quot;IIS Express&quot;: {
        ///			&quot;commandName&quot;: &quot;IISExpress&quot;,
        ///			&quot;environmentVariables&quot;: {
        ///				&quot;ASPNETCORE_ENVIRONMENT&quot;: &quot;Development&quot;
        ///			}
        ///		},
        ///		&quot;[Namespace]&quot;: {
        ///			&quot;commandName&quot;: &quot;Project&quot;,
        ///			&quot;environmentVariables&quot;: {
        ///				&quot;ASPNETCORE_ENVIRONMENT&quot;: &quot;Development&quot;
        ///			},
        ///			&quot;applicationUrl&quot;: &quot;http://localh [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string launchSettings {
            get {
                return ResourceManager.GetString("launchSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a using Microsoft.AspNetCore;
        ///using Microsoft.AspNetCore.Hosting;
        ///
        ///namespace [Namespace]
        ///{
        ///	public class Program
        ///	{
        ///		public static void Main(string[] args)
        ///		{
        ///			BuildWebHost(args).Run();
        ///		}
        ///
        ///		public static IWebHost BuildWebHost(string[] args) =&gt;
        ///			WebHost.CreateDefaultBuilder(args)
        ///				.UseStartup&lt;Startup&gt;()
        ///				.Build();
        ///	}
        ///}.
        /// </summary>
        internal static string Program {
            get {
                return ResourceManager.GetString("Program", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Web;
        ///
        ///namespace [Namespace].Helpers
        ///{
        ///	public class PropertyCopier
        ///	{
        ///		public static void CopyPropertyValues(object source, object destination)
        ///		{
        ///			var destProperties = destination.GetType().GetProperties();
        ///
        ///			foreach (var sourceProperty in source.GetType().GetProperties())
        ///			{
        ///				if (sourceProperty.GetValue(source, new object[] { }) != null)
        ///				{
        ///					foreach (var destProperty in destProperties)
        ///					 [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string PropertyCopier {
            get {
                return ResourceManager.GetString("PropertyCopier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a using EntitySearch;
        ///using Microsoft.EntityFrameworkCore;
        ///using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///
        ///namespace [Namespace].Helpers
        ///{
        ///	public class SearchHelper&lt;T&gt; where T : class
        ///	{
        ///		public static IQueryable&lt;T&gt; SearchFiltering(IQueryable&lt;T&gt; source, String field, String searchTerm, String searchOperator)
        ///		{
        ///			Operator soperator = Operator.Equals;
        ///			if (searchTerm != null)
        ///			{
        ///				if (searchTerm.Trim() != &quot;&quot;)
        ///				{
        ///					if (field != null)
        ///					{
        ///						if (field. [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string SearchHelper {
            get {
                return ResourceManager.GetString("SearchHelper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Microsoft Visual Studio Solution File, Format Version 12.00
        ///# Visual Studio 15
        ///VisualStudioVersion = 15.0.27130.2010
        ///MinimumVisualStudioVersion = 10.0.40219.1
        ///Project(&quot;{[AlphaGuid]}&quot;) = &quot;[Namespace]&quot;, &quot;[Namespace]\[Namespace].csproj&quot;, &quot;{[BetaGuid]}&quot;
        ///EndProject
        ///Global
        ///	GlobalSection(SolutionConfigurationPlatforms) = preSolution
        ///		Debug|Any CPU = Debug|Any CPU
        ///		Release|Any CPU = Release|Any CPU
        ///	EndGlobalSection
        ///	GlobalSection(ProjectConfigurationPlatforms) = postSolution
        ///		{[BetaGuid]}.Debug|Any [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string Solution {
            get {
                return ResourceManager.GetString("Solution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a using Microsoft.AspNetCore.Builder;
        ///using Microsoft.AspNetCore.Hosting;
        ///using Microsoft.Extensions.Configuration;
        ///using Microsoft.Extensions.DependencyInjection;
        ///using [Namespace].Models;
        ///using Microsoft.EntityFrameworkCore;
        ///
        ///namespace [Namespace]
        ///{
        ///	public class Startup
        ///	{
        ///		public Startup(IConfiguration configuration)
        ///		{
        ///			Configuration = configuration;
        ///		}
        ///
        ///		public IConfiguration Configuration { get; }
        ///
        ///		// This method gets called by the runtime. Use this method to add services to t [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string Startup {
            get {
                return ResourceManager.GetString("Startup", resourceCulture);
            }
        }
    }
}
